// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocationsFile():Promise<string>;

export function GetPrioritiesFile():Promise<string>;

export function Process():Promise<string>;

export function Reset():Promise<void>;

export function SelectLocationsFile():Promise<string>;

export function SelectPrioritiesFile():Promise<string>;

export function SetLocationsFile(arg1:string):Promise<void>;

export function SetPrioritiesFile(arg1:string):Promise<void>;
