// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocationsFile() {
  return window['go']['main']['App']['GetLocationsFile']();
}

export function GetPrioritiesFile() {
  return window['go']['main']['App']['GetPrioritiesFile']();
}

export function Process() {
  return window['go']['main']['App']['Process']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SelectLocationsFile() {
  return window['go']['main']['App']['SelectLocationsFile']();
}

export function SelectPrioritiesFile() {
  return window['go']['main']['App']['SelectPrioritiesFile']();
}

export function SetLocationsFile(arg1) {
  return window['go']['main']['App']['SetLocationsFile'](arg1);
}

export function SetPrioritiesFile(arg1) {
  return window['go']['main']['App']['SetPrioritiesFile'](arg1);
}
