// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Cancel():Promise<void>;

export function ClearCSV():Promise<void>;

export function ClearExcel():Promise<void>;

export function GetSelectedFiles():Promise<main.FileSelection>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function ProcessFiles():Promise<Record<string, any>>;

export function ValidateCSV(arg1:string):Promise<main.ValidationResult>;

export function ValidateExcel(arg1:string):Promise<main.ValidationResult>;
