// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function ClearCSV() {
  return window['go']['main']['App']['ClearCSV']();
}

export function ClearExcel() {
  return window['go']['main']['App']['ClearExcel']();
}

export function GetSelectedFiles() {
  return window['go']['main']['App']['GetSelectedFiles']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function ProcessFiles() {
  return window['go']['main']['App']['ProcessFiles']();
}

export function ValidateCSV(arg1) {
  return window['go']['main']['App']['ValidateCSV'](arg1);
}

export function ValidateExcel(arg1) {
  return window['go']['main']['App']['ValidateExcel'](arg1);
}
